networks:
  traefik-net:
    external: true

services:
  mahdibaghbani-nginx:
    image: ghcr.io/mahdibaghbani/mahdibaghbani.dev/nginx:latest
    container_name: "mahdibaghbani-nginx"
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    networks:
      traefik-net:
        ipv4_address: 172.16.4.2
    environment:
      SERVER_NAME: "mahdibaghbani.dev"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.mahdibaghbani-nginx.entrypoints=websecure"
      - "traefik.http.routers.mahdibaghbani-nginx.rule=Host(`mahdibaghbani.dev`, `www.mahdibaghbani.dev`)"
      - "traefik.http.routers.mahdibaghbani-nginx.service=mahdibaghbani-nginx"
      - "traefik.http.services.mahdibaghbani-nginx.loadbalancer.server.port=80"
  
  mahdibaghbani-goatcounter:
    image: ghcr.io/mahdibaghbani/mahdibaghbani.dev/goatcounter:latest
    container_name: "mahdibaghbani-goatcounter"
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    networks:
      traefik-net:
        ipv4_address: 172.16.4.3
    environment:
      GOATCOUNTER_DOMAIN: stats.mahdibaghbani.dev
      GOATCOUNTER_EMAIL: goatcounter@azadehafzar.io
      GOATCOUNTER_PASSWORD: pa55w0rdfewq215rfrZerj235<s3WZYVpeB52erte8e@a_DI9E8421aQ
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "${PWD}/volumes/goatcounter:/goatcounter/db"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.mahdibaghbani-goatcounter.entrypoints=websecure"
      - "traefik.http.routers.mahdibaghbani-goatcounter.rule=Host(`stats.mahdibaghbani.dev`)"
      - "traefik.http.routers.mahdibaghbani-goatcounter.service=mahdibaghbani-goatcounter"
      - "traefik.http.services.mahdibaghbani-goatcounter.loadbalancer.server.port=80"
